before_script:
  - apt-get update -qq && apt-get install -y -qq build-essential cmake bison flex libcmocka-dev python-pip
  - pip install sphinxcontrib-fulltoc sphinx sphinx_rtd_theme

stages:
  - build
  - docs

make:
  image: ubuntu
  stage: build
  artifacts:
    paths:
      - build/
  script:
    - mkdir build && cd build
    - cmake ..
    - make && make test

pages:
  image: ubuntu
  stage: docs
  dependencies:
    - make
  script:
    - cd build
    - make docs
    - mv html ../public
  artifacts:
    paths:
      - public
