stages:
  - build
  - docs

before_script:
  - apt-get update -qq && apt-get install -y -qq build-essential cmake bison flex libcmocka-dev python-pip libreadline-dev
  - pip install sphinxcontrib-fulltoc sphinx sphinx_rtd_theme

make:
  image: yottadb/yottadb-base
  stage: build
  artifacts:
    paths:
      - build/
      - /data/r1.*_x86_64/
    when: always
  script: ./tools/ci/build.sh

pages:
  image: yottadb/yottadb-base
  stage: docs
  dependencies:
    - make
  script: ./tools/ci/docs.sh
  artifacts:
    paths:
      - public
    when: always
