stages:
  - build
  - docs

make:
  image: charlescodes/yottadb-shell
  stage: build
  artifacts:
    paths:
      - build/
      - /data/r1.*_x86_64/
    when: always
  script: ./tools/ci/build.sh

pages:
  image: charlescodes/yottadb-shell
  stage: docs
  dependencies:
    - make
  script: ./tools/ci/docs.sh
  artifacts:
    paths:
      - public
    when: always
