before_script:
  - apt-get update -qq && apt-get install -y -qq build-essential cmake bison flex libcmocka-dev

stages:
  - build

make:
  image: ubuntu
  stage: build
  script:
    - mkdir build && cd build
    - cmake ../src/
    - make && make test
